#!/bin/bash
#
# Script that replaces the default hostname in files with the environments
# ${HOSTNAME} variable.
#
# This script is intended to be run before starting hbase-server to ensure
# that the hostname matches the configured environment variable. i.e.
# the -h --hostname flag.
#ifconfig | grep inet | grep -v 127.0.0.1 | grep -v localhost | cut -d" " -f10
#ifconfig | grep inet | grep -v 127.0.0.1 | grep -v localhost | cut -d"t" -f2 | cut -d" " -f2
#ifconfig | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -v 255 | grep -v 127
declare -a files=(
	'/opt/hbase/conf/hbase-site.xml'
	'/opt/hbase/conf/zoo.cfg'
)

# Optional custom hostname replacement
REPLACEMENT_HOSTNAME=${HBASE_DOCKER_HOSTNAME:-$HOSTNAME}

for file in "${files[@]}"; do
	if [ -f "${file}.bak" ]; then
		cp "${file}.bak" "${file}"
	else
		cp "${file}" "${file}.bak"
	fi

	sed -i "s/hbase-docker/${REPLACEMENT_HOSTNAME}/g" "${file}"
done
